id: 74558731970a476e92d350d2fd324f58
initial_creation_type: ocr
source_metadata:
  volumes:
    c792133533e442ea8101cfc21971c375:
      base_file: v074.txt
      image_group_id: I1PD95920
      title: བྱང་ཆུབ་སེམས་དཔའི་སའི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 75
