id: D6BFAB386
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:23:12+00:00'
last_modified: '2022-05-29T08:20:00.046708+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2440':
      image_group_id: I1PD95920
      title: བྱང་ཆུབ་སེམས་དཔའི་སའི་འགྲེལ་པ།
      total_pages: 1529
      order: 75
      base_file: 2440.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
